config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :employees
  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                   sessions: 'users/sessions' }
  devise_for :companies, path: 'companies', controllers: { registrations: 'companies/registrations',
                                                           sessions: 'companies/sessions' }
  namespace :employees do
    resources :sessions, only: %i[new create] do
      delete 'destroy', on: :collection
    end
  end
  resources :companies, only: %i[index show]
  resources :categories
  resources :products
  resources :suppliers
  resources :boards, except: :show do
    get 'positions', to: 'boards#positions', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  quantity    :integer
#  price       :decimal(, )
#  description :string
#  brand       :string
#  category_id :bigint(8)
#  supplier_id :bigint(8)
#  company_id  :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :category
  belongs_to :supplier
  belongs_to :company

  validates :name, :quantity, :price, :description, :brand, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_company!
  before_action :authenticate_admin!
  before_action :find_product, except: %i[new create index]

  def index
    @products = current_company.products
  end

  def new
    @product = current_company.products.new
  end

  def create
    @product = current_company.products.new(product_params)
    if @product.save
      flash[:notice] = 'Producto guardado exitosamente'
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Producto actualizado exitosamente'
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def show; end

  def destroy
    @product.destroy
    flash[:notice] = 'Producto eliminado exitosamente'
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :quantity, :price, :description, :brand, :category_id,
                                    :supplier_id)
  end

  def find_product
    @product = current_company.products.find(params[:id])
  end
end

app/views/products/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class = "text-center"><%= action %> producto</h1>
      <%= form_for(@product) do |product| %>
        <% if @product.errors.any? %>
          <div id="errors_explanation">
            <h2><%= pluralize(@product.errors.count,"error") %> No se pudo guardar este producto:</h2>
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= product.label :supplier_id %>
          <%= product.collection_select(:supplier_id, current_company.suppliers, :id, :name, { prompt:"Proveedor" }, { class: 'form-control'}) %>
          <%= link_to 'Crear proveedor', new_supplier_path %>
        </div>

        <div class="form-group">
          <%= product.label :category_id %>
          <%= product.collection_select(:category_id, current_company.categories, :id, :name, { prompt:"Categoría" }, { class: 'form-control'}) %>
          <%= link_to 'Crear categoría', new_category_path %>
        </div>

        <div class="form-group">
          <%= product.label :name %>
          <%= product.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= product.label :precio %>
          <%= product.number_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= product.label :quantity %>
          <%= product.number_field :quantity, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= product.label :brand %>
          <%= product.text_field :brand, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= product.label :description %>
          <%= product.text_area :description, class: "form-control" %>
        </div>

        <div class="actions">
          <%= link_to 'Cancelar', products_path, class: 'btn btn-default' %>
          <%= product.submit 'Guardar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>  
</div>

app/views/products/_product.html.erb
<tr id="product_<%= product.id %>">
  <td><%= product.id %></td>
  <td><%= product.name.titleize %></td>
  <td><%= product.quantity %></td>
  <td><%= product.price %></td>
  <td><%= product.description.capitalize %></td>
  <td><%= product.brand.capitalize %></td>
  <td><%= product.category.name.titleize %></td>
  <td><%= product.supplier.name.titleize %></td>
  <td><%= link_to 'Ver', product_path(product) %> -
      <%= link_to 'Editar', edit_product_path(product) %> -
      <%= link_to 'Eliminar', product_path(product), method: :delete, data: { confirm: 'Estas seguro?' } %>
  </td>
</tr>

app/views/products/edit.html.erb
<%= render 'form', action: 'Editar' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="d-flex justify-content-between align-items-center">
        <h1 class="text-center">Productos</h1>
        <%= link_to 'Crear producto', new_product_path, class: 'btn btn-primary float-right' %>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio unitario</th>
            <th>Descripción</th>
            <th>Marca</th>
            <th>Categoria</th>
            <th>Proveedor</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% if @products.empty? %>
            <tr><td class='text-center'>No hay productos creadas aun</td></tr>
          <% else %>
            <%= render @products %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form', action: 'Nuevo' %>

app/views/products/show.html.erb
<div class="container">  
  <div class="jumbotron">
    <h1 class="display-4"><%= @product.name.titleize %></h1>
    <p><strong>Descripción: </strong><%= @product.description.capitalize %></p>
    <p><strong>Cantidad: </strong><%= @product.quantity %></p>
    <p><strong>Precio: </strong><%= @product.price %></p>
    <p><strong>Marca: </strong><%= @product.brand.capitalize %></p>
    <p><strong>Categoría: </strong><%= @product.category.name %></p>
    <p><strong>Proveedor: </strong><%= @product.supplier.name %></p>
    <%= link_to 'Productos', products_path, class: 'btn btn-primary' %>
    <%= link_to 'Nuevo producto', new_product_path, class: 'btn btn-success' %>
  </div>
</div>