config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :employees
  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                   sessions: 'users/sessions' }
  devise_for :companies, path: 'companies', controllers: { registrations: 'companies/registrations',
                                                           sessions: 'companies/sessions' }
  namespace :employees do
    resources :sessions, only: %i[new create] do
      delete 'destroy', on: :collection
    end
  end
  resources :companies, only: %i[index show]
  resources :categories
  resources :products
  resources :suppliers
  resources :boards, except: :show do
    get 'positions', to: 'boards#positions', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message| %>
  <% unless message.blank? %>
    <div class="alert alert-<%= message_type(message_type) %> alert-dismissible fade show alert-growl" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><%= root_title %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_company && current_employee && policy(current_employee).admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"">
              Inventarios
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Categorías', categories_path, class: 'dropdown-item' %>
              <%= link_to 'Productos', products_path, class: 'dropdown-item' %>
              <%= link_to 'Proveedores', suppliers_path, class: 'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to 'Empleados', employees_path, class: 'nav-link' %>
          </li>
          <%= show_boards_button %>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_company %>
          <% if current_employee %>
            <li class="nav-item">
              <%= link_to "Salir #{current_employee.names.titleize}", employees_sessions_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Empleado', new_employees_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        <% end %>
        <% if current_session %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"">
              <%= user_signed_in? ? current_user.email.split('@')[0].capitalize : current_company.name.titleize %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <%= link_to 'Crear restaurante', new_company_registration_path, class: 'dropdown-item' %>
                <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                <%= link_to 'Salir', destroy_company_session_path, method: :delete, class: 'dropdown-item' %>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Registrate', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Entrar
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Restaurante', new_company_session_path, class: 'dropdown-item' %>
              <%= link_to 'Dueño', new_user_session_path, class: 'dropdown-item' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Njoy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js"></script>
  </head>
  <body class="application-layout">
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>